version: '3.1'

services:
  php:
    build: .
    volumes:
      - ./php:/var/www/html
    ports:
      - 8080:80
      - 4433:443 
    restart: always

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db23.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db
      MYSQL_USER: parrieta
      MYSQL_PASSWORD: Dollar2022

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
